services:
  web_api:
    build:
      context: ..
      dockerfile: ProjectMainV2.1/Dockerfile
    image: main-api
    container_name: main-api
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server_docker
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=test&Comp123Pass